[naver_entertain_movie]
title = "네이버TV연예 ─ 영화"
url = "https://entertain.naver.com/movie"
entrySelector = "ul[class='news_lst news_lst2'] li"
titleSelector = "div[class='tit_area'] a[class='tit']"
linkSelector = "div[class='tit_area'] a[class='tit']"
imageSelector = "li a[class='thumb_area'] img"
contentSelector = "div[class='tit_area'] p[class='summary']"

[daummovie_theater_y]
title = "다음영화 영화관 ─ 현재상영"
url = "https://movie.daum.net/premovie/theater?flag=Y"
entrySelector = "div.box_movie ol li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_theater_c]
title = "다음영화 영화관 ─ 개봉예정"
url = "https://movie.daum.net/premovie/theater?flag=C"
entrySelector = "div.box_movie ol li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_news_popular]
title = "다음영화 뉴스 ─ 인기"
url = "https://movie.daum.net/contents/news?type=popular"
entrySelector = "div.box_movienews > ol > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
waitUntil = "networkidle"

[daummovie_news_recent]
title = "다음영화 뉴스 ─ 최신"
url = "https://movie.daum.net/contents/news?type=recent"
entrySelector = "div.box_movienews > ul > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
waitUntil = "networkidle"

[kakaotv_preview]
title = "우리 영화 볼래?"
url = "https://tv.kakao.com/channel/462787/video"
entrySelector = "ul[class='list_vertical'] li"
titleSelector = "strong[class='tit_item']"
linkSelector = "a[class='link_contents']"
contentSelector = "span[class='mark_play']"
imageSelector = "img[class='thumb_img']"
waitUntil = "networkidle"

[navertv_moviepreview]
title = "네이버 영화 예고편 저장소"
url = "https://tv.naver.com/navermovie/clips"
entrySelector = "div div[class^='cds _MM_CARD']"
titleSelector = "dt[class='title'] > a > tooltip"
linkSelector = "dt[class='title'] a"
imageSelector = "div[class='cds_type'] a img"
contentSelector = "span[class='time']"

[naverpost_cine21_review]
title = "씨네21 ─ 20자평"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=520134&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_news]
title = "씨네21 ─ 국내뉴스"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=450865&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
