[naver_entertain_movie]
title = "네이버TV연예 ─ 영화"
url = "https://entertain.naver.com/movie"
entrySelector = "ul[class='news_lst news_lst2'] li"
titleSelector = "div[class='tit_area'] a[class='tit']"
linkSelector = "div[class='tit_area'] a[class='tit']"
imageSelector = "li a[class='thumb_area'] img"
contentSelector = "div[class='tit_area'] p[class='summary']"

[daummovie_theater_y]
title = "다음영화 영화관 ─ 현재상영"
url = "https://movie.daum.net/premovie/theater?flag=Y"
entrySelector = "div.box_movie ol li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_theater_c]
title = "다음영화 영화관 ─ 개봉예정"
url = "https://movie.daum.net/premovie/theater?flag=C"
entrySelector = "div.box_movie ol li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_news_popular]
title = "다음영화 뉴스 ─ 인기"
url = "https://movie.daum.net/contents/news?type=popular"
entrySelector = "div.box_movienews > ol > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
waitUntil = "networkidle"

[daummovie_news_recent]
title = "다음영화 뉴스 ─ 최신"
url = "https://movie.daum.net/contents/news?type=recent"
entrySelector = "div.box_movienews > ul > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
waitUntil = "networkidle"

[kakaotv_preview]
title = "우리 영화 볼래?"
url = "https://tv.kakao.com/channel/462787/video"
entrySelector = "ul[class='list_vertical'] li"
titleSelector = "strong[class='tit_item']"
linkSelector = "a[class='link_contents']"
contentSelector = "span[class='mark_play']"
imageSelector = "img[class='thumb_img']"
waitUntil = "networkidle"

[navertv_moviepreview]
title = "네이버 영화 예고편 저장소"
url = "https://tv.naver.com/navermovie/clips"
entrySelector = "div div[class^='cds _MM_CARD']"
titleSelector = "dt[class='title'] > a > tooltip"
linkSelector = "dt[class='title'] a"
imageSelector = "div[class='cds_type'] a img"
contentSelector = "span[class='time']"

[naverpost_cine21_review]
title = "씨네21 ─ 20자평"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=520134&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_news]
title = "씨네21 ─ 국내뉴스"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=450865&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[cgv_event_special]
title = "CGV ─ 이벤트 ─ SPECIAL"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=001"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[cgv_event_reservation]
title = "CGV ─ 이벤트 ─ 영화/예매"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=004"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[cgv_event_membership]
title = "CGV ─ 이벤트 ─ 멤버십/CLUB"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=008"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[cgv_event_theather]
title = "CGV ─ 이벤트 ─ CGV 극장별"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=005"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[cgv_event_partnership]
title = "CGV ─ 이벤트 ─ 제휴/할인"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=006"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[megabox_event_pick]
title = "메가박스 ─ 이벤트 ─ 메가Pick"
url = "https://www.megabox.co.kr/event/megabox"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[megabox_event_movie]
title = "메가박스 ─ 이벤트 ─ 영화"
url = "https://www.megabox.co.kr/event/movie"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a[data-no]"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[megabox_event_theater]
title = "메가박스 ─ 이벤트 ─ 극장"
url = "https://www.megabox.co.kr/event/theater"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a[data-no]"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[megabox_event_promotion]
title = "메가박스 ─ 이벤트 ─ 제휴/할인"
url = "https://www.megabox.co.kr/event/promotion"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a[data-no]"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[megabox_event_curtaincall]
title = "메가박스 ─ 이벤트 ─ 시사회/무대인사"
url = "https://www.megabox.co.kr/event/curtaincall"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a[data-no]"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[lottecinema_event_movie]
title = "롯데시네마 ─ 이벤트 ─ 영화"
url = "https://event.lottecinema.co.kr/NLCHS/Event/DetailList?code=20"
entrySelector = "ul.img_lst_wrap li"
titleSelector = "div.itm_date"
linkSelector = "a"
imageSelector = "img"
waitUntil = "networkidle"

[lottecinema_event_curtaincall]
title = "롯데시네마 ─ 이벤트 ─ 시사회/무대인사"
url = "https://event.lottecinema.co.kr/NLCHS/Event/DetailList?code=40"
entrySelector = "ul.img_lst_wrap li"
titleSelector = "div.itm_date"
linkSelector = "a"
imageSelector = "img"
waitUntil = "networkidle"

[lottecinema_event_hot]
title = "롯데시네마 ─ 이벤트 ─ HOT"
url = "https://event.lottecinema.co.kr/NLCHS/Event/DetailList?code=10"
entrySelector = "ul.img_lst_wrap li"
titleSelector = "div.itm_date"
linkSelector = "a"
imageSelector = "img"
waitUntil = "networkidle"

[lottecinema_event_promotion]
title = "롯데시네마 ─ 이벤트 ─ 제휴할인"
url = "https://event.lottecinema.co.kr/NLCHS/Event/DetailList?code=50"
entrySelector = "ul.img_lst_wrap li"
titleSelector = "div.itm_date"
linkSelector = "a"
imageSelector = "img"
waitUntil = "networkidle"

[lottecinema_event_nearcinema]
title = "롯데시네마 ─ 이벤트 ─ 우리동네 영화관"
url = "https://event.lottecinema.co.kr/NLCHS/Event/NearCinemaList"
entrySelector = "ul.ev_bn_wrap li"
titleSelector = "a.bn_tit"
contentSelector = "span.bn_tit_date"
waitUntil = "networkidle"

[extmovie_event]
title = "익스트림무비 ─ 시사회 ─ 시사회진행"
url = "https://extmovie.com/sisaing"
entrySelector = "ul li.list_unit"
titleSelector = "a.title_link"
linkSelector = "a.list_thumb"
imageSelector = "a.list_thumb img"
contentSelector = "p.list_summary"
waitUntil = "networkidle"
