[vlive_vscreen]
title = "V SCREEN"
url = "https://www.vlive.tv/channel/C956BB/board/5167"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
waitUntil = "networkidle"
