[vlive_vscreen]
title = "V SCREEN"
url = "https://www.vlive.tv/channel/C956BB/board/5167?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"

[daummovie_news_popular]
title = "다음영화 뉴스 ─ 인기"
url = "https://movie.daum.net/contents/news?type=popular"
entrySelector = "div.box_movienews > ol > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
waitUntil = "networkidle"

[daummovie_news_recent]
title = "다음영화 뉴스 ─ 최신"
url = "https://movie.daum.net/contents/news?type=recent"
entrySelector = "div.box_movienews > ul > li"
titleSelector = "strong a[class='link_txt']"
linkSelector = "strong a[class='link_txt']"
imageSelector = "span[class='bg_img']"
contentSelector = "p[class='desc_thumb'] a"
waitUntil = "networkidle"

[kakaotv_preview]
title = "우리 영화 볼래?"
url = "https://tv.kakao.com/channel/462787/video"
entrySelector = "div.inven_cont > ul > li"
titleSelector = "strong[class='tit_item']"
linkSelector = "li a[class='link_contents']"
imageSelector = "img[class='thumb_img']"
contentSelector = "span[data-raw-date]"

[navertv_moviepreview]
title = "네이버 영화 예고편 저장소"
url = "https://tv.naver.com/navermovie/clips"
entrySelector = "div div[class^='cds _MM_CARD']"
titleSelector = "dt[class='title'] > a > tooltip"
linkSelector = "dt[class='title'] a"
imageSelector = "div[class='cds_type'] a img"
contentSelector = "span[class='time']"
